context:
  version: "0.4.3"

package:
  name: tuios
  version: ${{ version }}

source:
  url: https://github.com/Gaurav-Gosain/tuios/archive/refs/tags/v${{ version }}.tar.gz
  sha256: be365d6a7568193655f2d049b2f2f95c8f27fd86bc3e6d15dca9429631ab5d12

build:
  number: 0
  script:
    - if: unix
      then:
        - cd $SRC_DIR
        - |
          go build -ldflags "-X main.version=${{ version }} -X main.commit=None -X main.date=None -X main.builtBy=conda-forge" \
            -o $PREFIX/bin/tuios ./cmd/tuios
        - go-licenses save $SRC_DIR/cmd/tuios --save_path=$RECIPE_DIR/license-files/tuios
        - |
          go build -ldflags "-X main.version=${{ version }} -X main.commit=None -X main.date=None -X main.builtBy=conda-forge" \
            -o $PREFIX/bin/tuios-web ./cmd/tuios-web
        - go-licenses save $SRC_DIR/cmd/tuios-web --save_path=$RECIPE_DIR/license-files/tuios-web
    - if: win
      then:
        - cd %SRC_DIR%
        - go build -ldflags "-X main.version=${{ version }} -X main.commit=unknown -X main.date=- -X main.builtBy=conda-forge" -o %PREFIX%/bin/tuios.exe ./cmd/tuios
        - go-licenses save %SRC_DIR%/cmd/tuios --save_path=%RECIPE_DIR%/license-files/tuios
        - go build -ldflags "-X main.version=${{ version }} -X main.commit=unknown -X main.date=- -X main.builtBy=conda-forge" -o %PREFIX%/bin/tuios-web.exe ./cmd/tuios-web
        - go-licenses save %SRC_DIR%/cmd/tuios-web --save_path=%RECIPE_DIR%/license-files/tuios-web

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - tuios --version
      - tuios-web --version

about:
  homepage: https://tuios.gaurav.zip/
  repository: https://github.com/Gaurav-Gosain/tuios
  summary: Terminal UI OS (Terminal Multiplexer)
  description: >
    TUIOS is a terminal-based window manager that provides a modern, efficient interface for managing multiple terminal sessions.
    Built with Go using the Charm stack (Bubble Tea v2 and Lipgloss v2), TUIOS offers a vim-like modal interface with comprehensive keyboard shortcuts, workspace support, and mouse interaction.
  license: MIT
  license_file:
    - LICENSE
    - license-files/tuios
    - license-files/tuios-web

extra:
  recipe-maintainers:
    - claudiushaag
